name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run shell script
      run: |
        echo "Using API key: $APIKEY"
        # Replace the following line with your actual command that uses the API key
        echo "Running example-command with API key: $APIKEY"
      env:
        APIKEY: ${{ secrets.APIKEY }}
